server:
  port: 8081
dubbo:
  registry:
    address: spring-cloud://localhost
  application:
    qos-enable: false
  cloud:
    subscribed-services: user-login-service,user-center-service
nacos:
  config:
    server-addr: 127.0.0.1:8848