name: lesson2
on:
  push:
    branches:
    - master
jobs:
  my-job1:
    name: test docker container
    runs-on: ubuntu-latest
    container: 
      image: node:8
    steps:
      - run: |
          echo ${{ vars.TT3 }}
        
