name: lesson3
on:
  push:
    branches:
    - master
jobs:
  my-job1:
    name: test env
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: |
          echo ${{ vars.V1 }}
        
